version: 2.1
jobs:

  swiftlint:
    docker:
      - image: bytesguy/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint lint --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml
          
  build-and-test:
    macos:
      xcode: 13.2.1
    environment:
      FL_OUTPUT_DIR: output

    steps:
      - checkout
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: LargeProject

      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output

workflows:
  build-test-lint:
    jobs:
      - swiftlint
      - build-and-test
